<?php
/**
 * Copyright (c) 2016. veldjmaxis <djmaxis@op.pl>
 */

//Without autoloader
include_once('Plugins/Video/Telewizjada/Telewizjada.php');
use djmaxis\Plugins\Video\Telewizjada\Telewizjada;

/**
 * For testing purposes only!!!
*/


//Create new Telewizjada object with autogenerated url to script file
$telewizjada = new Telewizjada($_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);

if($_GET['cid']){
    header('Content-Type: application/x-mpegurl');
    echo $telewizjada->getChannel(filter_input(INPUT_GET, 'cid', FILTER_VALIDATE_INT));
    exit;
}

if($_GET['epg']){
    echo $telewizjada->getEPG();
    exit;
}

echo $telewizjada->getChannelsList();
exit;
